### PR TITLE
Gitlab config

### PR DESCRIPTION
**Pull request by nasry**

### CODE REVIEW

**Comment by abessifi** [comment]
Thank you @nasry for your pull request :)
Indeed, I have some remarks/suggestions :

The 2 commits https://github.com/nasry/ansible-jhipster-devops/commit/9dbd7f419c31569ef9adbdefce3a454c7156d37b and https://github.com/nasry/ansible-jhipster-devops/commit/2dbac01b495c6cc1189076d219b6b07286ed9d52 which are included in the pull request seems to have a non descriptive titles (e.g Fix the docker-py version to 1.3.1 ||) which didn't reflect the feature(s) you implemented. I suggest that you squash these two commits into one and give it, for example, the name "Configure Gitlab with Docker".

According to the [gitlab.yml](https://github.com/nasry/ansible-jhipster-devops/blob/master/provisioning/gitlab.yml) file, the gitlab container is created twice (avoid code redundancy).
The first time when you call docker:

```
docker:
  docker_api_version: 1.18
  name: Gitlab
  image: sameersbn/gitlab:7.12.2-2
  state: present
```

The second time inside [docker-compose.yml](https://gist.githubusercontent.com/nasry/1c7197ee4aa1535be9b3/raw/de86d9e3df652b5ccfa6c2dd166df51ab963ab27/docker-compose.yml) file:

```
gitlab:
  image: sameersbn/gitlab:7.12.2-2
```

What I suggest at this level is we just use the docker-compose.yml (to be included in the project) to deploy the different containers/services.

Concerning data persistance, the volumes that are attached to each container, must be located on the /data partition of the host VM (cip-vm). E.g :

```
/vagrant/docker/gitlab/postgresql
should be
/data/docker/gitlab/postgresql
```

On the other hand, I think it would be better to fix the version of some stuff (for stability and maintenance purposes) :

`sameersbn/gitlab:7.12.2-2` this is not a good version to pick up (it is a revision tag). It would be better to choose an x.y.z one. The "latest" tag is to avoid too. You can use the `sameersbn/gitlab:7.13.1` instead.
Same thing for the `redis` image to use.

**Comment by nasry** [comment]
Hello Ahmed :)
Yes I've made some mistakes , concerning the two commits you are right, I think because I am not well familiar with Git yet .
Concerning the gitlab configuration , I've not followed correctly the documentation.
Now I  have   "Configure Gitlab with Docker" commit https://github.com/nasry/ansible-jhipster-devops/commit/23e14d267490ed4e5254a965d84b0057f1eb8c78 in which I corrected the mistakes I made  and a new pull request was made .

**Comment by abessifi** [comment]
Thanks @nasry for your quick reply.
I'll checkout your PR and test it eventually.

**Comment by nasry** [comment]
3asléma Ahmed ;
as always tot7éfni b nasa27ék  :D
As you are right I will take your advice certainly ;) ,

Contributionnement :p

2015-07-27 19:30 GMT+01:00 Ahmed Bessifi <notifications@github.com>:

**Comment by abessifi** [comment]
I run "vagrant up cip-vm" but it seems not working at all. Ansible passes successfully :

TASK: [Create necessary directories] *****************************************\* 
ok: [cip-vm] => (item=/data/docker/gitlab/postgresql)
ok: [cip-vm] => (item=/data/docker/gitlab/gitlab)
ok: [cip-vm] => (item=/data/docker/gitlab/redis)

TASK: [Install Docker-compose] ***********************************************\* 
changed: [cip-vm]

TASK: [Deploy GitLab container using docker-compose] *************************\* 
changed: [cip-vm]

PLAY RECAP *******************************************************************\* 
cip-vm                     : ok=13   changed=3    unreachable=0    failed=0

But on the cip-vm there are no containers or images.

**Comment by nasry** [comment]
sorry for the delay , it's exactly what I am looking for now the "Can't find a suitable configuration" problem and I noticed that when I removed the "&"
I tried to work with docker compose provisonner ( cfg.vm.provision :docker_compose, yml: Dir.getwd+"/provisioning/docker-compose.yml", run: "always" ) but it can't find the docker-compose.yml file . I doubt that is  due to the mismatch between docker doemon and librery python docker-py !
anyway thanks for the help :)

**Comment by abessifi** [comment]
Update some stuff.
PR merged and tested https://github.com/abessifi/ansible-jhipster-devops/commit/9517a1be2127cc53abe2c675ca913df2336bcc26 .

**Comment by nasry** [comment]
Bonjour abessifi/ansible-jhi,

J’aimerais vous inviter à rejoindre mon réseau professionnel sur LinkedIn.

Achref

Veuillez confirmer que vous connaissez Achref: https://www.linkedin.com/e/v2?e=0-ipnodtj0-53&t=ssuw&tracking=eml-guest-invite-cta&ek=invite_guest&sharedKey=AMcxexmJ&invitationId=6150553267953811456








Vous avez reçu une invitation à rejoindre un réseau. LinkedIn utilise votre adresse e-mail pour faire des suggestions à ses utilisateurs dans des fonctionnalités telles que Les connaissez-vous ? Se désabonner ici : https://www.linkedin.com/e/v2?e=0-ipnodtj0-53&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQFzq7dQoIYRtAAAAVVsnr0bgae7t7CwHGD9F5puWcxIfaHJFbkx6Sdb6M-EYuX7ceUQMBW_VxoCnw-SPeNeVjWG697Pw3ptQ2gOptlLmpbaF_jwZBACr96L9C7THHmgISteJ0cmh44HMU8bUGg5GUygt29Yh98A-M8J3HAZM4ZS7ZYH8EUCS1pN3wcYhM8EWRrP&eid=0-ipnodtj0-53


Cet e-mail est destiné à reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-ipnodtj0-53&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View, CA 94043, USA. LinkedIn et le logo de LinkedIn sont des marques déposées de LinkedIn.

**Comment by nasry** [comment]
Achref Nasri would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/e/v2?e=-7oq04g-ipxrdbfe-yl&t=ssuw&ek=first_guest_reminder_01&li=14&m=hero&ts=accept_text&sharedKey=AMcxexmJ&invitationId=6150553267953811456

View Achref Nasri&#39;s profile: https://www.linkedin.com/e/v2?e=-7oq04g-ipxrdbfe-yl&t=ssuw&ek=first_guest_reminder_01&li=3&m=hero&ts=profile_text&sharedKey=AMcxexmJ&invitationId=6150553267953811456

abessifi/ansible-jhi,

J’aimerais vous inviter à rejoindre mon réseau professionnel sur LinkedIn.





Vous avez reçu une invitation à rejoindre un réseau. LinkedIn utilise votre adresse e-mail pour faire des suggestions à ses utilisateurs dans des fonctionnalités telles que Les connaissez-vous ? Se désabonner ici : https://www.linkedin.com/e/v2?e=-7oq04g-ipxrdbfe-yl&t=lun&midToken=AQFmrFVhGEd36Q&ek=first_guest_reminder_01&li=16&m=unsub&ts=HTML&eid=-7oq04g-ipxrdbfe-yl&loid=AQGMCPlcyguDGQAAAVWR9CobZGyGHoMvGVcStBt7WhcECz5b5yqsrF9YtGMB76LK3AN7i9yShw8L9vk9KUgiiySbrpWwmA2ztHvd4weOBz_W7G0yDGuTUUVZU5sb_xHTZtBTr4ZyqVV1GUvlPjHxgKQMq-yJLxHPkO-JcF8Wmr3kCBcVc-AsRCAZZ8zhU0PfLRZc

Cet e-mail est destiné à reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=-7oq04g-ipxrdbfe-yl&a=customerServiceUrl&ek=first_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View, CA 94043, USA. LinkedIn et le logo de LinkedIn sont des marques déposées de LinkedIn.

**Pull request closed without merging**
